version: 2
updates:
  - package-ecosystem: gomod
    directory: backend/
    commit-message:
      prefix: [deps]
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: organizer/
    commit-message:
      prefix: [deps]
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: frontend/
    commit-message:
      prefix: [deps]
    schedule:
      interval: weekly
