openapi: 3.0.3
info:
  title: Movie and TV Show Manager API
  description: API for managing movie and TV show searches, wishlist, downloads, and file organization
  version: 1.0.0

paths:
  /api/indexers:
    get:
      summary: Retrieve available Prowlarr indexers
      responses:
        '200':
          description: A list of indexers
          content:
            application/json:
              schema:
                type: object
                properties:
                  indexers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

  /api/categories:
    get:
      summary: Retrieve available Prowlarr categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string

  /api/search:
    post:
      summary: Search for movies and TV shows
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                isIMDbID:
                  type: boolean
                indexers:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
                minSizeGB:
                  type: number
                  format: float
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        indexer:
                          type: string
                        size:
                          type: number
                          format: float

  /api/search/add-to-wishlist:
    post:
      summary: Add a search query to the wishlist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                isIMDbID:
                  type: boolean
                indexers:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
                minSizeGB:
                  type: number
                  format: float
      responses:
        '200':
          description: Wishlist item added
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/search/download:
    post:
      summary: Initiate download of a selected search result
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resultID:
                  type: string
                downloader:
                  type: string
      responses:
        '200':
          description: Download initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/wishlist:
    get:
      summary: Retrieve the current wishlist
      responses:
        '200':
          description: A list of wishlist items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        query:
                          type: string
                        status:
                          type: string

  /api/wishlist/{id}:
    delete:
      summary: Remove an item from the wishlist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item removed from wishlist
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

    put:
      summary: Edit a wishlist item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                isIMDbID:
                  type: boolean
                indexers:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
                minSizeGB:
                  type: number
                  format: float
      responses:
        '200':
          description: Wishlist item updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /api/downloads:
    get:
      summary: Retrieve list of completed downloads
      responses:
        '200':
          description: List of downloaded torrents
          content:
            application/json:
              schema:
                type: object
                properties:
                  downloads:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        status:
                          type: string
                        files:
                          type: array
                          items:
                            type: object
                            properties:
                              fileName:
                                type: string

  /api/downloads/copy:
    post:
      summary: Copy downloaded files to a library directory with a new name
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                downloads:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      newName:
                        type: string
                      library:
                        type: string
      responses:
        '200':
          description: Files copied to library directory
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
