name: On PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Run backend tests
      run: |
        go test -v ./...
      working-directory: ./backend

    - name: Run organizer/jav-actor tests
      run: |
        go test -v ./...
      working-directory: ./organizer/jav-actor

    - name: Run frontend formatter check, linter and tests
      run: |
        npm ci
        npx prettier --check .
        npx eslint .
        npx vitest run
      working-directory: ./frontend
