name: Go Tests On Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Run backend tests
      run: |
        go test -v ./...
      working-directory: ./backend
      env:
        MTEAM_API_KEY: ${{ secrets.MTEAM_API_KEY }}

    - name: Run organizer tests
      run: |
        go test -v ./...
      working-directory: ./organizer

    - name: Run frontend formatter check and linter
      run: |
        npm ci
        npx prettier --check .
        npx eslint .
      working-directory: ./frontend
