name: On Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Run backend tests
      run: |
        go test -v ./...
      working-directory: ./backend
      env:
        MTEAM_API_KEY: ${{ secrets.MTEAM_API_KEY }}

    - name: Run organizer/jav-actor tests
      run: |
        go test -v ./...
      working-directory: ./organizer/jav-actor

    - name: Run frontend formatter check, linter and tests
      run: |
        npm ci
        npx prettier --check .
        npx eslint .
        npx vitest run
      working-directory: ./frontend

    - name: Run organizer/file-organizer check, linter and tests
      run: |
        uv uv sync --locked --all-extras --dev
        uvx ruff check .
        uvx ruff format . --check
        uv run pytest
      working-directory: ./organizer/file-organizer
